name: Release packages
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Daily auto-update packages
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up reprepro
      env: 
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
        GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        R2_URL: ${{ secrets.R2_URL }}
        R2_ACCESS_KEY: ${{ secrets.R2_ACCESS_KEY }}
        R2_SECRET_KEY: ${{ secrets.R2_SECRET_KEY }}
        R2_BUCKET: ${{ secrets.R2_BUCKET }}
      run: |
        sudo apt-get update
        sudo apt-get install -y gnupg2 wget s3fs ruby
        git clone https://github.com/OpsPT/deb-s3.git /tmp/deb-s3
        cd /tmp/deb-s3
        bundle install
        cd -
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        for dir in */
        do
          cd "${dir%/}/"
          archs=$(yq -r .archs[] opspt.vars.yml)
          codenames=$(yq -r .codenames[] opspt.vars.yml)
          version=$(tail -n 1 opspt.version)
          rm -rf dist
          make -f opspt.mk build_if_updated
          if [ -d "dist" ]; then
            cd dist
            for codename in $codenames; do
              for arch in $archs; do
                reprepro --outdir ./s3mount includedeb "${codename}" "./${dir%/}_${codename}_${arch}_${version}.deb" 
                deb-s3 upload --bucket $R2_BUCKET --access-key $R2_ACCESS_KEY --secret-key $R2_SECRET_KEY --url $R2_URL --codename $codename --arch $arch --sign=$GPG_KEY_ID "./${dir%/}_${codename}_${arch}_${version}.deb"
              done
            done
            sed -i 's/BUILDED=FALSE/BUILDED=TRUE/g' ../opspt.version;
            cd ..
          fi
          cd ..
        done
        git remote set-url origin "https://$GH_TOKEN@github.com/opsPT/apt.git"
        git add .
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update build statuses"
          git push
        fi
