name: Release packages
on:
  push:
    branches:
      - main
  workflow_run:
    workflows:
      - Daily auto-update packages
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up reprepro
      env: 
        GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
      run: |
        sudo apt-get update
        sudo apt-get install -y reprepro gnupg2 wget
        sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        sudo chmod +x /usr/local/bin/yq
        echo -n "$GPG_SIGNING_KEY" | base64 --decode | gpg --import
        for dir in */
        do
          cd "${dir%/}/"
          archs=$(yq -r .archs[] opspt.vars.yml)
          codenames=$(yq -r .codenames[] opspt.vars.yml)
          version=$(tail -n 1 opspt.version)
          rm -rf dist
          make -f opspt.mk build_if_updated
          if [ -d "dist" ]; then
            cd dist
            mkdir conf
            for arch in $archs; do
              for codename in $codenames; do
                rm -f conf/distributions 
                cp ../opspt.distributions conf/distributions
                sed -i -e "s/%arch%/${arch}/g" -e "s/%codename%/${codename}/g" conf/distributions
                cat conf/distributions
                reprepro export
                # Build debian packages
                reprepro includedeb "${codename}" "./${dir%/}_${codename}_${arch}_${version}.deb"
              done
            done
            cd ..
          fi
          cd ..
        done
